# Cross-lingual transfer: English supervision → Turkish news

Fine-tunes an encoder on an English political-bias news dataset with stratified 5-fold cross-validation, evaluates it in English, then applies the fold ensemble zero-shot to the Turkish test set used in the main notebook. This is the cross-lingual experiment reported in the paper.

In [2]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
! pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.4 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [5]:
import json
import numpy as np
import pandas as pd
import os, random, json
import numpy as np
import pandas as pd
import torch

from datasets import Dataset
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)

In [6]:
os.environ["WANDB_DISABLED"] = "true"

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

print("cuda_available:", torch.cuda.is_available())
print("torch.version.cuda:", torch.version.cuda)

cuda_available: True
torch.version.cuda: 12.6

In [7]:
import pandas as pd

df = pd.read_json(
    "news_article_dataset.json",
    lines=True,          # 🔥 ÖNEMLİ
    encoding="utf-8"
)

print(df.shape)
print(df.columns)
print(df.head())

(8478, 14)
Index(['Title of Headline Roundup', 'description', 'Topics', 'Date',
       'url_story', 'left_story_title', 'center_story_title',
       'right_story_title', 'right_story_url', 'right_story_text',
       'center_story_url', 'center_story_text', 'left_story_url',
       'left_story_text'],
      dtype='object')
   Title of Headline Roundup description       Topics       Date  \
0           Romney in London        None    Elections 2012-07-26
1     Romney's Overseas Trip        None    Elections 2012-08-01
2  Biden Comment Controversy        None    Elections 2012-08-16
3               Romney Taxes        None    Elections 2012-08-17
4  Skinnydipping Congressman        None  US Congress 2012-08-20

                          url_story  \
0              /story/romney-london
1      /story/romneys-overseas-trip
2  /story/biden-comment-controversy
3               /story/romney-taxes
4  /story/skinnydipping-congressman

                                    left_story_title  \
0                      Romney's Olympics false start
1  Was Romney's trip 'a great success' or gaffe-f...
2            Mission Impossible: Managing Joe Biden
3  Obama Campaign Wants Romney To Release 5 Years...
4  Exclusive: FBI probed GOP trip with drinking, ...

                                  center_story_title  \
0              Shaky Start for Romney Overseas Trip
1    Romney's Overseas Trip Produces Hits and Misses
2  Campaign Trail: Biden's Comment About 'Chains'...
3  Romney Says He Paid A Tax Rate Of At Least 13 ...
4  Congressman Who Took Nude Dip In Sea Of Galile...

                                   right_story_title  \
0  Romney causes London stir over Olympic readine...
1                  RomneyÃ¢â‚¬â„¢s trip a bumpy ride
2  Ryan takes on Obama campaign over Biden 'chain...
3  Romney campaign doesn't bite on Obama tax retu...
4  Account of overseas skinny-dipping fuels clari...

                                     right_story_url  \
0  http://politics.blogs.foxnews.com/2012/07/26/r...
1  http://www.washingtontimes.com/news/2012/jul/3...
2  http://www.foxnews.com/politics/2012/08/15/oba...
3  http://www.foxnews.com/politics/2012/08/17/oba...
4  http://www.foxnews.com/politics/2012/08/20/rep...

                                    right_story_text  \
0  The Brits, taking a break from beating up on t...
1  Under mounting pressure to be more open on for...
2  Paul Ryan is taking on the Obama campaign dire...
3  The Obama campaign made an unusual offer to Mi...
4  A bizarre report about Republican congressmen ...

                                    center_story_url  \
0  http://online.wsj.com/article/SB10000872396390...
1  http://online.wsj.com/article/SB10000872396390...
2  http://www.npr.org/blogs/thetwo-way/2012/08/15...
3  http://www.npr.org/blogs/itsallpolitics/2012/0...
4  http://www.npr.org/blogs/thetwo-way/2012/08/20...

                                   center_story_text  \
0  Mitt Romney launched an overseas tour Thursday...
1  WARSAWâ€”With a speech lauding Poland as a "de...
2  By telling a racially mixed audience in Virgin...
3  Republican presidential candidate Mitt Romney ...
4  Saying he apologizes for "any embarrassment I ...

                                      left_story_url  \
0  http://politicalticker.blogs.cnn.com/2012/07/2...
1  http://www.cnn.com/2012/07/31/politics/romney-...
2  http://www.politico.com/news/stories/0812/7977...
3  http://www.huffingtonpost.com/2012/08/17/obama...
4  http://www.politico.com/news/stories/0812/7986...

                                     left_story_text
0  Mitt Romney told British leaders he hopes to t...
1  OPINION\nWarsaw (CNN) -- In the estimation of ...
2  The most emotionally powerful minute of Joe Bi...
3  With the spotlight back on Mitt Romney's tax r...
4  The FBI probed a late-night swim in the Sea of...

In [8]:
print("Raw df shape:", df.shape)
print(df.columns)

Raw df shape: (8478, 14)
Index(['Title of Headline Roundup', 'description', 'Topics', 'Date',
       'url_story', 'left_story_title', 'center_story_title',
       'right_story_title', 'right_story_url', 'right_story_text',
       'center_story_url', 'center_story_text', 'left_story_url',
       'left_story_text'],
      dtype='object')

In [9]:
print(df.columns)
print(df.head(3))

Index(['Title of Headline Roundup', 'description', 'Topics', 'Date',
       'url_story', 'left_story_title', 'center_story_title',
       'right_story_title', 'right_story_url', 'right_story_text',
       'center_story_url', 'center_story_text', 'left_story_url',
       'left_story_text'],
      dtype='object')
   Title of Headline Roundup description     Topics       Date  \
0           Romney in London        None  Elections 2012-07-26
1     Romney's Overseas Trip        None  Elections 2012-08-01
2  Biden Comment Controversy        None  Elections 2012-08-16

                          url_story  \
0              /story/romney-london
1      /story/romneys-overseas-trip
2  /story/biden-comment-controversy

                                    left_story_title  \
0                      Romney's Olympics false start
1  Was Romney's trip 'a great success' or gaffe-f...
2            Mission Impossible: Managing Joe Biden

                                  center_story_title  \
0              Shaky Start for Romney Overseas Trip
1    Romney's Overseas Trip Produces Hits and Misses
2  Campaign Trail: Biden's Comment About 'Chains'...

                                   right_story_title  \
0  Romney causes London stir over Olympic readine...
1                  RomneyÃ¢â‚¬â„¢s trip a bumpy ride
2  Ryan takes on Obama campaign over Biden 'chain...

                                     right_story_url  \
0  http://politics.blogs.foxnews.com/2012/07/26/r...
1  http://www.washingtontimes.com/news/2012/jul/3...
2  http://www.foxnews.com/politics/2012/08/15/oba...

                                    right_story_text  \
0  The Brits, taking a break from beating up on t...
1  Under mounting pressure to be more open on for...
2  Paul Ryan is taking on the Obama campaign dire...

                                    center_story_url  \
0  http://online.wsj.com/article/SB10000872396390...
1  http://online.wsj.com/article/SB10000872396390...
2  http://www.npr.org/blogs/thetwo-way/2012/08/15...

                                   center_story_text  \
0  Mitt Romney launched an overseas tour Thursday...
1  WARSAWâ€”With a speech lauding Poland as a "de...
2  By telling a racially mixed audience in Virgin...

                                      left_story_url  \
0  http://politicalticker.blogs.cnn.com/2012/07/2...
1  http://www.cnn.com/2012/07/31/politics/romney-...
2  http://www.politico.com/news/stories/0812/7977...

                                     left_story_text
0  Mitt Romney told British leaders he hopes to t...
1  OPINION\nWarsaw (CNN) -- In the estimation of ...
2  The most emotionally powerful minute of Joe Bi...

In [10]:
# ==========================================================
# 2) WIDE -> LONG (same idea: build one text column + label)
# ==========================================================
rows = []
for _, row in df.iterrows():
    if pd.notna(row.get("left_story_text", None)) and str(row["left_story_text"]).strip():
        rows.append({"text": row["left_story_text"], "bias_label": "left"})
    if pd.notna(row.get("center_story_text", None)) and str(row["center_story_text"]).strip():
        rows.append({"text": row["center_story_text"], "bias_label": "center"})
    if pd.notna(row.get("right_story_text", None)) and str(row["right_story_text"]).strip():
        rows.append({"text": row["right_story_text"], "bias_label": "right"})

df_long = pd.DataFrame(rows).dropna().reset_index(drop=True)
print("df_long shape:", df_long.shape)
print(df_long["bias_label"].value_counts())

df_long shape: (24505, 2)
bias_label
left      8430
right     8375
center    7700
Name: count, dtype: int64

In [11]:
# =========================================
# 3) LABEL MAP (same as TR)
# =========================================
label2id = {"left": 0, "center": 1, "right": 2}
id2label = {v: k for k, v in label2id.items()}

df_long = df_long[df_long["bias_label"].isin(label2id)].copy()
df_long["label"] = df_long["bias_label"].map(label2id)

In [12]:
# ===================================================
from sklearn.model_selection import train_test_split

temp_df, test_df = train_test_split(
    df_long[["text", "label"]],
    test_size=0.20,
    random_state=SEED,
    stratify=df_long["label"]
)
print(f"Train+Val (temp_df): {temp_df.shape}, Test (test_df): {test_df.shape}")

Train+Val (temp_df): (19604, 2), Test (test_df): (4901, 2)

In [13]:
! pip install evaluate

Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

In [14]:
# =========================================
# 5) XLM-R CV ENSEMBLE (TR clone)
# =========================================
import evaluate
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix

In [15]:
# =========================================
# 5) XLM-R CV ENSEMBLE (TR clone)
# =========================================
import evaluate
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix

# ---- CONFIG (same style) ----
MODEL_NAME    = "xlm-roberta-base"
MAX_LENGTH    = 128
BATCH_SIZE    = 16
NUM_EPOCHS    = 20
LEARNING_RATE = 1e-5
N_SPLITS      = 5

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_LENGTH
    )

accuracy = evaluate.load("accuracy")
f1_mac   = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1_macro": f1_mac.compute(predictions=preds, references=labels, average="macro")["f1"]
    }

# ---- Fixed hold-out test set (same) ----
test_ds = Dataset.from_pandas(test_df.reset_index(drop=True)) \
    .map(tokenize, batched=True) \
    .remove_columns(["text"]) \
    .with_format("torch")

# ---- CV setup on temp_df (same) ----
X, y = temp_df["text"].values, temp_df["label"].values
skf  = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)

fold_results, best_ckpts = [], []

# save per-fold logits like TR code
LOG_DIR = "en_xlmr_logits"
os.makedirs(LOG_DIR, exist_ok=True)

for fold, (tr_idx, vl_idx) in enumerate(skf.split(X, y), 1):
    print(f"\n===== FOLD {fold}/{N_SPLITS} =====")

    tr_ds = Dataset.from_pandas(temp_df.iloc[tr_idx].reset_index(drop=True)) \
        .map(tokenize, batched=True) \
        .remove_columns(["text"]) \
        .with_format("torch")

    vl_ds = Dataset.from_pandas(temp_df.iloc[vl_idx].reset_index(drop=True)) \
        .map(tokenize, batched=True) \
        .remove_columns(["text"]) \
        .with_format("torch")

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(id2label),
        id2label={int(k): str(v) for k, v in id2label.items()},
        label2id={str(k): int(v) for k, v in label2id.items()},
        # English base checkpoint is already CLS, so no need for ignore_mismatched_sizes
    )

    args = TrainingArguments(
        output_dir=f"./en_xlmr_cv_fold_{fold}",
        eval_strategy="epoch",
        logging_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=1,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=NUM_EPOCHS,
        weight_decay=0.05,
        seed=SEED,
        report_to=[]
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=tr_ds,
        eval_dataset=vl_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
    )

    trainer.train()
    fold_results.append(trainer.evaluate())
    best_ckpts.append(trainer.state.best_model_checkpoint)

    # dump raw test logits for this fold (same)
    pr_test = trainer.predict(test_ds)
    np.save(f"{LOG_DIR}/logits_fold{fold}.npy", pr_test.predictions.astype("float32"))

# ---- CV Summary (same) ----
cv_df = pd.DataFrame(fold_results)
print("\n===== CV MEAN METRICS =====\n", cv_df.mean(numeric_only=True))

# ---- Soft voting ensemble on test set (same) ----
all_logits = []
for fold in range(1, N_SPLITS + 1):
    all_logits.append(np.load(f"{LOG_DIR}/logits_fold{fold}.npy"))

avg_logits = np.mean(np.stack(all_logits, axis=0), axis=0)
y_pred_ens = np.argmax(avg_logits, axis=1)
y_true     = test_ds["label"]

print("\n ENSEMBLE CLASSIFICATION REPORT:\n",
      classification_report(y_true, y_pred_ens,
                            target_names=[id2label[i] for i in range(len(id2label))]))
print("\nConfusion Matrix:\n", confusion_matrix(y_true, y_pred_ens))

===== FOLD 1/5 =====

===== FOLD 2/5 =====

===== FOLD 3/5 =====

===== FOLD 4/5 =====

===== FOLD 5/5 =====

===== CV MEAN METRICS =====
 eval_loss                    0.963138
eval_accuracy                0.544736
eval_f1_macro                0.541880
eval_runtime                 7.403000
eval_samples_per_second    529.724000
eval_steps_per_second       33.208800
epoch                        6.200000
dtype: float64

 ENSEMBLE CLASSIFICATION REPORT:
               precision    recall  f1-score   support

        left       0.58      0.55      0.56      1686
      center       0.55      0.51      0.53      1540
       right       0.57      0.64      0.60      1675

    accuracy                           0.57      4901
   macro avg       0.57      0.57      0.57      4901
weighted avg       0.57      0.57      0.57      4901


Confusion Matrix:
 [[ 920  342  424]
 [ 369  791  380]
 [ 298  303 1074]]

In [16]:
import os, shutil
from google.colab import drive

drive.mount("/content/drive")

# 1) en iyi fold checkpoint (eval_loss en düşük) seç
best_fold_idx = int(np.argmin([r["eval_loss"] for r in fold_results]))  # 0-based
best_path = best_ckpts[best_fold_idx]
print("Best fold checkpoint:", best_path)

# 2) Drive’a export klasörü
EXPORT_DIR = "/content/drive/MyDrive/en_xlmr_ft_best"
if os.path.exists(EXPORT_DIR):
    shutil.rmtree(EXPORT_DIR)

# 3) model + tokenizer save
best_model = AutoModelForSequenceClassification.from_pretrained(best_path)
best_model.save_pretrained(EXPORT_DIR)
tokenizer.save_pretrained(EXPORT_DIR)

print("Saved to:", EXPORT_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Best fold checkpoint: ./en_xlmr_cv_fold_4/checkpoint-2943
Saved to: /content/drive/MyDrive/en_xlmr_ft_best

## Zero-shot evaluation on the Turkish test set

In [17]:
import pandas as pd, hashlib, uuid
from sklearn.model_selection import train_test_split

SEED = 42

RAW_CSV = "all_sources_combined_by_keywords.csv"

df_raw = pd.read_csv(RAW_CSV).iloc[:, :7]

allowed_sources = ["BirGün", "Sözcü", "Habertürk", "Euronews",
                   "Milliyet", "Diriliş Postası"]
df_raw = df_raw[df_raw["Source"].isin(allowed_sources)].reset_index(drop=True)

cols_keep = ["Source", "Title", "URL", "Content", "search_keyword"]
df = df_raw[cols_keep].copy()

# 30 kelime filtresi
df = df[df["Content"].apply(lambda x: isinstance(x, str) and len(x.split()) >= 30)]
df.reset_index(drop=True, inplace=True)

bias_map = {
    "BirGün": "left",
    "Sözcü": "left",
    "Habertürk": "center",
    "Euronews": "center",
    "Milliyet": "right",
    "Diriliş Postası": "right"
}
df["bias_label"] = df["Source"].map(bias_map)

label2id = {"left": 0, "center": 1, "right": 2}
id2label = {v: k for k, v in label2id.items()}

df["label"] = df["bias_label"].map(label2id)

In [18]:
temp_df_tr, test_df_tr = train_test_split(
    df[["Content", "label"]],
    test_size=0.20,
    random_state=SEED,
    stratify=df["label"]
)

print("TR Train+Val:", temp_df_tr.shape)
print("TR Test:", test_df_tr.shape)

TR Train+Val: (2330, 2)
TR Test: (583, 2)

In [19]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer
from datasets import Dataset
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
MODEL_DIR = "/content/drive/MyDrive/en_xlmr_ft_best"

tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR, use_fast=True)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_DIR,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

In [21]:
def tokenize_tr(batch):
    return tokenizer(
        batch["Content"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

tr_test_ds = Dataset.from_pandas(
    test_df_tr.reset_index(drop=True)
).map(
    tokenize_tr, batched=True
).remove_columns(
    ["Content"]
).with_format("torch")

In [22]:
trainer = Trainer(
    model=model,
    tokenizer=tokenizer
)

pred = trainer.predict(tr_test_ds)

logits = pred.predictions
y_true = pred.label_ids
y_pred = np.argmax(logits, axis=1)

In [23]:
print("\n=== English FT model → Turkish TEST set ===\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=[id2label[i] for i in range(3)]
))

print("Confusion Matrix:\n",
      confusion_matrix(y_true, y_pred))

=== English FT model → Turkish TEST set ===

              precision    recall  f1-score   support

        left       0.28      0.03      0.06       223
      center       0.37      0.33      0.35       163
       right       0.36      0.75      0.48       197

    accuracy                           0.36       583
   macro avg       0.34      0.37      0.30       583
weighted avg       0.33      0.36      0.28       583

Confusion Matrix:
 [[  7  48 168]
 [ 12  54  97]
 [  6  44 147]]

In [24]:
np.save("logits_en_ft_on_tr_test.npy", logits.astype("float32"))
np.save("labels_tr_test.npy", y_true.astype("int16"))

In [25]:

# =========================================
# 6) BASELINE (pre-trained, no FT) (same)
# =========================================
print("\n Baseline (pre-trained) evaluation...")

baseline_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

baseline_trainer = Trainer(
    model=baseline_model,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

baseline_preds   = baseline_trainer.predict(test_ds)
baseline_logits  = baseline_preds.predictions
baseline_labels  = baseline_preds.label_ids
baseline_y_pred  = np.argmax(baseline_logits, axis=1)

print("\n BASELINE Classification Report:")
print(classification_report(
    baseline_labels,
    baseline_y_pred,
    target_names=[id2label[i] for i in range(3)]
))

cm_base = confusion_matrix(baseline_labels, baseline_y_pred)
print("\nConfusion Matrix - Baseline:\n", cm_base)

# Optional: save logits like TR
np.save("logits_en_xlmr.npy", avg_logits.astype(np.float32))
print("Saved ensemble logits -> logits_en_xlmr.npy")

 Baseline (pre-trained) evaluation...

 BASELINE Classification Report:
              precision    recall  f1-score   support

        left       0.00      0.00      0.00      1686
      center       0.00      0.00      0.00      1540
       right       0.34      1.00      0.51      1675

    accuracy                           0.34      4901
   macro avg       0.11      0.33      0.17      4901
weighted avg       0.12      0.34      0.17      4901


Confusion Matrix - Baseline:
 [[   0    0 1686]
 [   0    0 1540]
 [   0    0 1675]]
Saved ensemble logits -> logits_en_xlmr.npy